### ISSUE TITLE
[META] Ideas 💡

### ISSUE THREAD

**Issue by moul** [moul/git-ci#2]
* [ ] find a way to get rid of the `-github-user-session` arg or make it easier and safer to get it
* [ ] `git ci wait`: blocks until all checks are passed; exit 0 if everything is green, expected usage: `git push && git ci wait && git merge`
* [ ] use "unique" color per job to make the multi-stream easier to read
* [ ] use real job names as line prefix
* [ ] supports calling the command early and progressively detect new checks
* [ ] subscribe to an activity stream to get real-time events
* [ ] support more drivers
* [ ] doc and examples
* [ ] tests & maintainability improvements
